'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Bell,Check,Eye,EyeOff,Loader2,Newspaper,Pencil,Plus,Save,Sparkles,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {toast} from 'sonner';
import {translator,locale} from '@/lib/i18n';
import {contentFields,type Announcement,type SiteContent} from '@/lib/content';
import type {Lang,Product} from '@/lib/catalog';

type Update=(body:Record<string,unknown>)=>Promise<boolean>;
type Promo={code:string;active:number};
const languages=[['uz','O‘zbekcha'],['ru','Русский'],['en','English']] as const;
function LanguageTabs({value,onChange}:{value:Lang;onChange:(v:Lang)=>void}){
 return <Tabs value={value} onValueChange={v=>onChange(v as Lang)}><TabsList className="editor-language-tabs">{languages.map(([id,name])=><TabsTrigger key={id} value={id}>{name}</TabsTrigger>)}</TabsList></Tabs>;
}

export function ContentEditor({lang,content,products,busy,update}:{lang:Lang;content:SiteContent;products:Product[];busy:boolean;update:Update}){
 const t=translator(lang),[draft,setDraft]=useState(content),[editLang,setEditLang]=useState<Lang>(lang),[dirty,setDirty]=useState(false);
 useEffect(()=>{if(!dirty)setDraft(content);},[content,dirty]);
 const featured=products.find(p=>p.id===draft.heroProductId),activeProducts=products.filter(p=>p.active);
 async function save(e:FormEvent){e.preventDefault();if(await update({action:'siteContent',content:draft}))setDirty(false);}
 return <div className="content-editor"><div className="admin-section-heading"><div><h2>{t('adminContent')}</h2><p className="admin-description">{t('contentIntro')}</p></div></div><div className="content-editor-layout"><form className="editor-form" onSubmit={save}><LanguageTabs value={editLang} onChange={setEditLang}/><div className="editor-fields">{contentFields.map(field=><label key={field.key}>{t(field.label)}{field.multiline?<textarea lang={editLang} rows={field.key==='aboutText'?5:2} required maxLength={field.max} value={draft.texts[field.key][editLang]} onChange={e=>{setDraft(prev=>({...prev,texts:{...prev.texts,[field.key]:{...prev.texts[field.key],[editLang]:e.target.value}}}));setDirty(true);}}/>:<input lang={editLang} required maxLength={field.max} value={draft.texts[field.key][editLang]} onChange={e=>{setDraft(prev=>({...prev,texts:{...prev.texts,[field.key]:{...prev.texts[field.key],[editLang]:e.target.value}}}));setDirty(true);}}/>}</label>)}</div><div className="editor-save"><span>{dirty?t('unsavedChanges'):t('saved')}</span><button className="outline-button" type="button" disabled={busy||!dirty} onClick={()=>{setDraft(content);setDirty(false);}}>{t('discardChanges')}</button><button className="primary-button" disabled={busy||!dirty}>{busy?<Loader2 size={16} className="spin"/>:<Save size={16}/>} {t('save')}</button></div></form><aside className="editor-featured"><h3>{t('contentPreview')}</h3><div className="editor-banner-preview"><span>{draft.texts.heroEyebrow[editLang]}</span><h3>{draft.texts.heroTitle[editLang]}</h3><p>{draft.texts.heroSubtitle[editLang]}</p>{featured&&<img src={featured.image} alt={featured.name[editLang]}/>}<span className="preview-button">{draft.texts.heroButton[editLang]}</span></div><label>{t('contentHeroProduct')}<Select value={draft.heroProductId} onValueChange={value=>{setDraft(prev=>({...prev,heroProductId:value}));setDirty(true);}}><SelectTrigger className="form-select"><SelectValue/></SelectTrigger><SelectContent>{activeProducts.map(p=><SelectItem key={p.id} value={p.id}>{p.name[lang]}</SelectItem>)}</SelectContent></Select></label><label>{t('contentHeroTarget')}<Select value={draft.heroTarget} onValueChange={value=>{setDraft(prev=>({...prev,heroTarget:value as SiteContent['heroTarget']}));setDirty(true);}}><SelectTrigger className="form-select"><SelectValue/></SelectTrigger><SelectContent>{(['sale','all','electronics','fashion','home','beauty','sport'] as const).map(key=><SelectItem key={key} value={key}>{t(key)}</SelectItem>)}</SelectContent></Select></label></aside></div></div>;
}

export function AnnouncementManager({lang,announcements,promos,busy,update}:{lang:Lang;announcements:Announcement[];promos:Promo[];busy:boolean;update:Update}){
 const t=translator(lang),[editing,setEditing]=useState<Announcement|null>(null),[editLang,setEditLang]=useState<Lang>(lang);
 function create(){setEditLang(lang);setEditing({id:crypto.randomUUID(),title:{uz:'',ru:'',en:''},body:{uz:'',ru:'',en:''},kind:'news',promoCode:'',published:0,revision:1,createdAt:'',updatedAt:'',read:false});}
 function open(a:Announcement){setEditLang(lang);setEditing({...a,title:{...a.title},body:{...a.body}});}
 function payload(a:Announcement,published=!!a.published){return {action:'announcement',id:a.id,title:a.title,body:a.body,kind:a.kind,promoCode:a.promoCode,published};}
 async function save(e:FormEvent){e.preventDefault();if(!editing)return;const missing=languages.find(([id])=>editing.title[id].trim().length<2||!editing.body[id].trim());if(missing){setEditLang(missing[0]);toast.error(t('announcementLanguages'));return;}if(await update(payload(editing)))setEditing(null);}
 return <section><div className="admin-section-heading"><div><h2>{t('adminAnnouncements')}</h2><p className="admin-description">{t('announcementIntro')}</p></div><button className="primary-button" disabled={busy} onClick={create}><Plus size={17}/>{t('newAnnouncement')}</button></div>{announcements.length?<div className="admin-announcements">{announcements.map(a=><article className="admin-announcement-card" key={a.id}><span className={'announcement-symbol '+a.kind}>{a.kind==='promotion'?<Sparkles size={22}/>:<Newspaper size={22}/>}</span><div><div className="announcement-meta"><span className={'status-pill '+(a.published?'status-delivered':'status-pending')}>{a.published?<Eye size={12}/>:<EyeOff size={12}/>} {t(a.published?'published':'draft')}</span><span>{t(a.kind==='promotion'?'announcementPromotion':'announcementNews')}</span><time>{new Date(a.updatedAt).toLocaleDateString(locale(lang))}</time></div><h3>{a.title[lang]}</h3><p>{a.body[lang]}</p>{a.promoCode&&<span className="announcement-promo">{a.promoCode}</span>}</div><div className="announcement-actions"><button className="outline-button small-button" disabled={busy} onClick={()=>open(a)}><Pencil size={14}/>{t('editAnnouncement')}</button>{!!a.published&&<button className="text-button" disabled={busy} onClick={()=>void update(payload(a,false))}><EyeOff size={14}/>{t('hideAnnouncement')}</button>}</div></article>)}</div>:<div className="admin-table-card"><Empty><EmptyHeader><EmptyMedia><Bell size={34}/></EmptyMedia><EmptyTitle>{t('noAnnouncements')}</EmptyTitle><EmptyDescription>{t('announcementIntro')}</EmptyDescription></EmptyHeader><button className="primary-button" onClick={create}><Plus size={17}/>{t('newAnnouncement')}</button></Empty></div>}
 <Dialog open={!!editing} onOpenChange={v=>!v&&setEditing(null)}><DialogContent className="announcement-editor-dialog" showCloseButton={false}><button className="modal-close" aria-label={t('close')} onClick={()=>setEditing(null)}><X size={20}/></button><DialogTitle>{editing?.createdAt?t('editAnnouncement'):t('newAnnouncement')}</DialogTitle><DialogDescription>{t('announcementLanguages')}</DialogDescription>{editing&&<form className="editor-form announcement-editor-form" onSubmit={save}><LanguageTabs value={editLang} onChange={setEditLang}/><label>{t('announcementTitle')}<input lang={editLang} required minLength={2} maxLength={140} value={editing.title[editLang]} onChange={e=>setEditing({...editing,title:{...editing.title,[editLang]:e.target.value}})}/></label><label>{t('announcementBody')}<textarea lang={editLang} required rows={6} maxLength={3000} value={editing.body[editLang]} onChange={e=>setEditing({...editing,body:{...editing.body,[editLang]:e.target.value}})}/></label><div className="form-grid"><label>{t('announcementKind')}<Select value={editing.kind} onValueChange={v=>setEditing({...editing,kind:v as Announcement['kind'],promoCode:v==='news'?'':editing.promoCode})}><SelectTrigger className="form-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="news">{t('announcementNews')}</SelectItem><SelectItem value="promotion">{t('announcementPromotion')}</SelectItem></SelectContent></Select></label>{editing.kind==='promotion'&&<label>{t('optionalPromo')}<Select value={editing.promoCode||'none'} onValueChange={v=>setEditing({...editing,promoCode:v==='none'?'':v})}><SelectTrigger className="form-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">{t('noPromo')}</SelectItem>{promos.map(p=><SelectItem key={p.code} value={p.code} disabled={!p.active}>{p.code}</SelectItem>)}</SelectContent></Select></label>}</div><label className="check-label"><Checkbox checked={!!editing.published} onCheckedChange={v=>setEditing({...editing,published:v===true?1:0})}/>{t('publishAnnouncement')}</label><div className="announcement-editor-footer"><span className={'status-pill '+(editing.published?'status-delivered':'status-pending')}>{t(editing.published?'published':'draft')}</span><button className="primary-button" disabled={busy}>{busy?<Loader2 size={16} className="spin"/>:<Check size={16}/>} {t(editing.published?'publish':'save')}</button></div></form>}</DialogContent></Dialog></section>;
}
