'use client';
import {useState,useEffect,type FormEvent} from 'react';
import {Package,ShoppingBag,MessageCircle,Plus,Pencil,X,Loader2,CheckCircle2,Ticket,BarChart3,Search,LockKeyhole,Settings,Newspaper} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Empty,EmptyHeader,EmptyMedia,EmptyTitle} from '@/components/ui/empty';
import {translator,locale,type TranslationKey} from '@/lib/i18n';
import {type Lang,type Product,type Order,type Message,type Category} from '@/lib/catalog';
import {requestApi} from '@/lib/client-api';
import {toast} from 'sonner';
import {defaultContent,type Announcement,type SiteContent} from '@/lib/content';
import {ContentEditor,AnnouncementManager} from './admin-content';
type Promo={code:string;percent:number;cap:number;active:number};
type AdminData={orders:Order[];messages:Message[];promos:Promo[];content:SiteContent;announcements:Announcement[]};
export default function AdminPanel({lang,products,isAdmin,refresh,onSupport}:{lang:Lang;products:Product[];isAdmin:boolean;refresh:()=>Promise<unknown>;onSupport:()=>void}){
 const t=translator(lang),money=(n:number)=>new Intl.NumberFormat(locale(lang)).format(n);
 const [data,setData]=useState<AdminData>({orders:[],messages:[],promos:[],content:defaultContent,announcements:[]}),[tab,setTab]=useState('orders'),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Product|null>(null),[detail,setDetail]=useState<Order|null>(null),[category,setCategory]=useState<Category>('electronics'),[active,setActive]=useState(true),[target,setTarget]=useState(''),[reply,setReply]=useState(''),[q,setQ]=useState(''),[promoCode,setPromoCode]=useState(''),[promoPercent,setPromoPercent]=useState(10),[promoCap,setPromoCap]=useState(150000),[error,setError]=useState(false),[ready,setReady]=useState(false);
 async function load(){try{setData(await requestApi<AdminData>(undefined,'admin'));setError(false);setReady(true);}catch{setError(true);}}
 useEffect(()=>{if(isAdmin)void load();},[isAdmin]);
 useEffect(()=>{if(!isAdmin)return;const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer);},[isAdmin]);
 async function update(body:Record<string,unknown>){setBusy(true);try{await requestApi(body);await load();await refresh();toast.success(t('saved'));return true;}catch(e){toast.error(t(e instanceof Error&&['invalidData','notAdmin','stockError','invalidPromo'].includes(e.message)?e.message as TranslationKey:'error'));return false;}finally{setBusy(false);}}
 function openEdit(p:Product){setEditing(p);setCategory(p.category);setActive(!!p.active);}
 function createProduct(){openEdit({id:'new-'+Date.now().toString(36),name:{uz:'',ru:'',en:''},description:{uz:'',ru:'',en:''},brand:'',category:'electronics',price:0,oldPrice:0,image:'',stock:0,active:1,isNew:1,featured:0,variants:['standard']});}
 async function saveProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await update({action:'product',id:editing?.id,name:{uz:f.get('uz'),ru:f.get('ru'),en:f.get('en')},description:{uz:f.get('descriptionUz'),ru:f.get('descriptionRu'),en:f.get('descriptionEn')},brand:f.get('brand'),category,price:Number(f.get('price')),oldPrice:Number(f.get('oldPrice')),stock:Number(f.get('stock')),image:f.get('image'),active}))setEditing(null);}
 const threads=Array.from(new Set(data.messages.map(m=>m.user_id))).map(id=>({id,last:data.messages.filter(m=>m.user_id===id).at(-1)!,name:data.orders.find(o=>o.user_id===id)?.name||id.slice(-8)}));
 const pending=data.orders.filter(o=>o.status==='pending').length;
 const filteredOrders=data.orders.filter(o=>!q||(o.number+' '+o.name+' '+o.phone).toLowerCase().includes(q.toLowerCase()));
 const filteredProducts=products.filter(p=>!q||Object.values(p.name).join(' ').toLowerCase().includes(q.toLowerCase()));
 const transitions:Record<string,string[]>={pending:['confirmed','cancelled'],confirmed:['shipping','cancelled'],shipping:['delivered'],delivered:[],cancelled:[]};
 const empty=(key:TranslationKey)=><Empty><EmptyHeader><EmptyMedia><Package size={32}/></EmptyMedia><EmptyTitle>{t(key)}</EmptyTitle></EmptyHeader></Empty>;
 if(!isAdmin)return <div className="signin-card"><LockKeyhole size={40}/><h2>{t('notAdmin')}</h2><button className="primary-button" onClick={onSupport}>{t('contactAdmin')}</button></div>;
 return <section className="admin-page"><div className="page-heading"><div><span className="admin-eyebrow">SHOPLAND / {t('overview').toUpperCase()}</span><h1>{t('admin')}</h1></div><button className="outline-button" disabled={busy} onClick={()=>void load()}>{t('retry')}</button></div>{error&&<div className="error-banner">{t('loadError')}<button onClick={()=>void load()}>{t('retry')}</button></div>}<div className="admin-metrics"><article><span><ShoppingBag size={20}/>{t('ordersCount')}</span><strong>{data.orders.length}</strong><small>{pending} · {t('status_pending')}</small></article><article><span><BarChart3 size={20}/>{t('orderValue')}</span><strong>{money(data.orders.filter(o=>o.status!=='cancelled').reduce((n,o)=>n+o.total,0))}<small> {t('sum')}</small></strong></article><article><span><Package size={20}/>{t('activeProducts')}</span><strong>{products.filter(p=>p.active).length}</strong></article><article><span><MessageCircle size={20}/>{t('openMessages')}</span><strong>{threads.filter(t=>t.last.sender==='customer').length}</strong></article></div><Tabs value={tab} onValueChange={v=>{setTab(v);setQ('');}} className="admin-tabs"><div className="admin-toolbar"><TabsList variant="line"><TabsTrigger value="orders"><ShoppingBag size={16}/>{t('adminOrders')}</TabsTrigger><TabsTrigger value="products"><Package size={16}/>{t('adminProducts')}</TabsTrigger><TabsTrigger value="support"><MessageCircle size={16}/>{t('adminSupport')}</TabsTrigger><TabsTrigger value="promos"><Ticket size={16}/>{t('adminPromos')}</TabsTrigger><TabsTrigger value="content"><Settings size={16}/>{t('adminContent')}</TabsTrigger><TabsTrigger value="announcements"><Newspaper size={16}/>{t('adminAnnouncements')}</TabsTrigger></TabsList>{(tab==='orders'||tab==='products')&&<label className="admin-search"><Search size={17}/><input placeholder={t('searchAction')} aria-label={t('searchAction')} value={q} onChange={e=>setQ(e.target.value)}/></label>}</div><TabsContent value="orders"><div className="admin-table-card">{filteredOrders.length?<Table><TableHeader><TableRow><TableHead>{t('orderNumber')}</TableHead><TableHead>{t('customerLabel')}</TableHead><TableHead>{t('date')}</TableHead><TableHead>{t('total')}</TableHead><TableHead>{t('status')}</TableHead><TableHead>{t('details')}</TableHead></TableRow></TableHeader><TableBody>{filteredOrders.map(o=><TableRow key={o.id}><TableCell><strong>{o.number}</strong></TableCell><TableCell>{o.name}<small className="cell-small">{o.phone}</small></TableCell><TableCell>{new Date(o.created_at).toLocaleDateString(locale(lang))}</TableCell><TableCell>{money(o.total)} {t('sum')}</TableCell><TableCell><span className={'status-pill status-'+o.status}>{t(('status_'+o.status) as TranslationKey)}</span></TableCell><TableCell><button className="outline-button small-button" onClick={()=>setDetail(o)}>{t('details')}</button></TableCell></TableRow>)}</TableBody></Table>:empty('noOrders')}</div></TabsContent>
 <TabsContent value="products"><div className="admin-section-heading"><h2>{products.length} {t('results')}</h2><button className="primary-button" onClick={createProduct}><Plus size={17}/>{t('addProduct')}</button></div><div className="admin-table-card"><Table><TableHeader><TableRow><TableHead>{t('products')}</TableHead><TableHead>{t('category')}</TableHead><TableHead>{t('price')}</TableHead><TableHead>{t('stock')}</TableHead><TableHead>{t('active')}</TableHead><TableHead>{t('editProduct')}</TableHead></TableRow></TableHeader><TableBody>{filteredProducts.map(p=><TableRow key={p.id}><TableCell><span className="table-product"><img src={p.image} alt={p.name[lang]}/><span>{p.name[lang]}<small>{p.brand}</small></span></span></TableCell><TableCell>{t(p.category)}</TableCell><TableCell>{money(p.price)} {t('sum')}</TableCell><TableCell>{p.stock}</TableCell><TableCell><Checkbox aria-label={t('active')+' '+p.name[lang]} checked={!!p.active} disabled={busy} onCheckedChange={v=>void update({action:'product',...p,active:v===true})}/></TableCell><TableCell><button className="icon-button" onClick={()=>openEdit(p)} aria-label={t('editProduct')}><Pencil size={17}/></button></TableCell></TableRow>)}</TableBody></Table></div></TabsContent>
 <TabsContent value="support"><div className="admin-support"><aside>{threads.length?threads.map(th=><button className={th.id===target?'active':''} key={th.id} onClick={()=>setTarget(th.id)}><span className="thread-avatar"><UserInitial value={th.name}/></span><span><b>{th.name}</b><small>{th.last.body.slice(0,55)}</small></span>{th.last.sender==='customer'&&<i className="unanswered"/>}</button>):empty('emptySupport')}</aside><div className="admin-thread">{target?<><div className="chat-header"><b>{threads.find(th=>th.id===target)?.name}</b><MessageCircle size={18}/></div><div className="chat-messages">{data.messages.filter(m=>m.user_id===target).map(m=><div className={'chat-message '+(m.sender==='admin'?'own':'')} key={m.id}><small>{t(m.sender==='admin'?'administrator':'customerLabel')}</small><p>{m.body}</p><time>{new Date(m.created_at).toLocaleString(locale(lang))}</time></div>)}</div><form className="chat-form" onSubmit={async e=>{e.preventDefault();if(await update({action:'message',userId:target,body:reply}))setReply('');}}><textarea placeholder={t('reply')} aria-label={t('reply')} value={reply} onChange={e=>setReply(e.target.value)} maxLength={2000} required rows={2}/><button className="primary-button" disabled={busy||!reply.trim()}>{t('send')}</button></form></>:empty('conversation')}</div></div></TabsContent>
 <TabsContent value="promos"><div className="promo-admin-layout"><div className="admin-table-card"><Table><TableHeader><TableRow><TableHead>{t('promoCode')}</TableHead><TableHead>{t('promoPercent')}</TableHead><TableHead>{t('promoCap')}</TableHead><TableHead>{t('active')}</TableHead></TableRow></TableHeader><TableBody>{data.promos.map(p=><TableRow key={p.code}><TableCell><strong>{p.code}</strong></TableCell><TableCell>{p.percent}%</TableCell><TableCell>{money(p.cap)} {t('sum')}</TableCell><TableCell><Checkbox checked={!!p.active} disabled={busy} aria-label={p.code+' '+t('active')} onCheckedChange={v=>void update({action:'promoUpdate',...p,active:v===true})}/></TableCell></TableRow>)}</TableBody></Table></div><form className="promo-admin-form" onSubmit={async e=>{e.preventDefault();if(await update({action:'promoUpdate',code:promoCode,percent:promoPercent,cap:promoCap,active:true}))setPromoCode('');}}><h3>{t('promo')}</h3><label>{t('promoCode')}<input required minLength={2} maxLength={32} pattern="[A-Z0-9_-]+" placeholder="SHOP10" value={promoCode} onChange={e=>setPromoCode(e.target.value.toUpperCase())}/></label><label>{t('promoPercent')}<input required type="number" min={1} max={90} value={promoPercent} onChange={e=>setPromoPercent(Number(e.target.value))}/></label><label>{t('promoCap')}<input required type="number" min={1} max={100000000} value={promoCap} onChange={e=>setPromoCap(Number(e.target.value))}/></label><button className="primary-button" disabled={busy}>{t('save')}</button></form></div></TabsContent><TabsContent value="content">{ready?<ContentEditor lang={lang} content={data.content} products={products} busy={busy} update={update}/>:<p role="status">{t('loading')}</p>}</TabsContent><TabsContent value="announcements">{ready?<AnnouncementManager lang={lang} announcements={data.announcements} promos={data.promos} busy={busy} update={update}/>:<p role="status">{t('loading')}</p>}</TabsContent></Tabs>
 <Dialog open={!!editing} onOpenChange={v=>!v&&setEditing(null)}><DialogContent className="edit-product-dialog" showCloseButton={false}><button className="modal-close" onClick={()=>setEditing(null)} aria-label={t('close')}><X size={20}/></button><DialogTitle>{t('editProduct')}</DialogTitle><DialogDescription>{editing?.id}</DialogDescription>{editing&&<form className="edit-product-form" onSubmit={saveProduct}><div className="form-grid"><label className="span-two">{t('nameUz')}<input name="uz" required minLength={2} maxLength={150} defaultValue={editing.name.uz}/></label><label>{t('nameRu')}<input name="ru" required minLength={2} maxLength={150} defaultValue={editing.name.ru}/></label><label>{t('nameEn')}<input name="en" required minLength={2} maxLength={150} defaultValue={editing.name.en}/></label>{(['uz','ru','en'] as Lang[]).map((l,i)=><label className="span-two" key={l}>{t('description')} · {['O‘zbekcha','Русский','English'][i]}<textarea name={['descriptionUz','descriptionRu','descriptionEn'][i]} required maxLength={3000} rows={3} defaultValue={editing.description[l]}/></label>)}<label>{t('brand')}<input name="brand" required maxLength={60} defaultValue={editing.brand}/></label><label>{t('category')}<Select value={category} onValueChange={v=>setCategory(v as Category)}><SelectTrigger className="form-select"><SelectValue/></SelectTrigger><SelectContent>{(['electronics','fashion','home','beauty','sport'] as Category[]).map(c=><SelectItem key={c} value={c}>{t(c)}</SelectItem>)}</SelectContent></Select></label><label>{t('price')}<input type="number" required min={1} max={100000000} name="price" defaultValue={editing.price}/></label><label>{t('oldPrice')}<input type="number" required min={0} max={100000000} name="oldPrice" defaultValue={editing.oldPrice}/></label><label>{t('stock')}<input type="number" required min={0} max={100000} name="stock" defaultValue={editing.stock}/></label><label className="span-two">{t('imageUrl')}<input required name="image" maxLength={1500} defaultValue={editing.image} placeholder="https://…"/></label></div><label className="check-label"><Checkbox checked={active} onCheckedChange={v=>setActive(v===true)}/>{t('active')}</label><button className="primary-button full-width" disabled={busy}>{busy&&<Loader2 size={16} className="spin"/>}{t('save')}</button></form>}</DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="order-detail-dialog" showCloseButton={false}><button className="modal-close" onClick={()=>setDetail(null)} aria-label={t('close')}><X size={20}/></button><DialogTitle>{detail?.number}</DialogTitle><DialogDescription>{t('orderItems')}</DialogDescription>{detail&&<><span className={'status-pill status-'+detail.status}>{t(('status_'+detail.status) as TranslationKey)}</span>{detail.items.map((i,n)=><div className="receipt-item" key={n}><img src={i.image} alt={i.name[lang]}/><span>{i.name[lang]}<small>{i.quantity} × {money(i.price)} {t('sum')}{i.variant!=='standard'?' · '+i.variant:''}</small></span></div>)}<dl className="admin-order-data"><dt>{t('fullName')}</dt><dd>{detail.name}</dd><dt>{t('phone')}</dt><dd>{detail.phone}</dd><dt>{t('address')}</dt><dd>{detail.city}, {detail.address==='pickup'?t('pickup'):detail.address}</dd><dt>{t('paymentMethod')}</dt><dd>{t(detail.payment as TranslationKey)}</dd>{detail.note&&<><dt>{t('note')}</dt><dd>{detail.note}</dd></>}</dl><div className="summary-total"><span>{t('total')}</span><b>{money(detail.total)} {t('sum')}</b></div><div className="status-actions">{transitions[detail.status]?.map(status=><button disabled={busy} key={status} className={status==='cancelled'?'outline-button danger':'primary-button'} onClick={async()=>{if(await update({action:'orderStatus',id:detail.id,status})){setDetail({...detail,status});}}}><CheckCircle2 size={16}/>{t(('status_'+status) as TranslationKey)}</button>)}</div></>}</DialogContent></Dialog>
 </section>;
}
function UserInitial({value}:{value:string}){return <>{value.slice(0,1).toUpperCase()}</>;}
